Report for diagram : 00 Anlagenüberwachung
associated Config File: ..\config.txt

Task Complete: False     3 out of 24(12.5%) processed    total time: 2.9
3 FAILED    0 Successfully created    0 WARNINGS 

1.   plant code: AES.223    time: 2020-05-13 16:00:27.052720    duration:40.037681    !!!ERROR Could not create diagram!!! : plant has no datapoints
2.   plant code: AES.406    time: 2020-05-13 16:00:39.810503    duration:12.757783    !!!ERROR!!! Ecxeption:Traceback (most recent call last):   File "C:/Users/Brokamp/PycharmProjects/ENEFFCO-diagramm-creator/code/diagram_creator.py", line 600, in main     return_value = new_diagram(driver, plant, diagram.name, diagram.template_path, diagram.hierarchical_codes, diagram.diagram_type)   File "C:/Users/Brokamp/PycharmProjects/ENEFFCO-diagramm-creator/code/diagram_creator.py", line 207, in new_diagram     af.go_to_ChartPage(driver)   File "C:\Users\Brokamp\PycharmProjects\ENEFFCO-diagramm-creator\code\additional_functions.py", line 55, in go_to_ChartPage     wait_loading_finished() TypeError: wait_loading_finished() missing 2 required positional arguments: 'driver' and 'time_before_start' 
3.   plant code: AES.329    time: 2020-05-13 16:00:55.057528    duration:15.246025    !!!ERROR!!! Ecxeption:Traceback (most recent call last):   File "C:/Users/Brokamp/PycharmProjects/ENEFFCO-diagramm-creator/code/diagram_creator.py", line 600, in main     return_value = new_diagram(driver, plant, diagram.name, diagram.template_path, diagram.hierarchical_codes, diagram.diagram_type)   File "C:/Users/Brokamp/PycharmProjects/ENEFFCO-diagramm-creator/code/diagram_creator.py", line 216, in new_diagram     uppload_completed = upload_defintion(driver, template_path, diagram_name)   File "C:/Users/Brokamp/PycharmProjects/ENEFFCO-diagramm-creator/code/diagram_creator.py", line 365, in upload_defintion     upload_definition_button = driver.find_element_by_id('SplitMain_ContentPlaceHolderBodyRight_ContentTabControl_ContentTabCallBackPanel_ContentPanel_ctl07_InstContentPanel_InstFolderDisplay_InstFolderDisplayCP_ctl00_ctl00_ctl00')   File "C:\Users\Brokamp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id     return self.find_element(by=By.ID, value=id_)   File "C:\Users\Brokamp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element     'value': value})['value']   File "C:\Users\Brokamp\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute     self.error_handler.check_response(response)   File "C:\Users\Brokamp\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response     raise exception_class(message, screen, stacktrace) selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="SplitMain_ContentPlaceHolderBodyRight_ContentTabControl_ContentTabCallBackPanel_ContentPanel_ctl07_InstContentPanel_InstFolderDisplay_InstFolderDisplayCP_ctl00_ctl00_ctl00"]"}   (Session info: chrome=81.0.4044.138)  
